# -*- coding: utf-8 -*-
"""board

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13W3dKAOt4_JxS0sjeFv3hopguM4BZIqN
"""

def board():
    print(topRow)
    print(middleRow)
    print(bottomRow)

topRow = ['-', '-', '-']
middleRow = ['-', '-', '-']
bottomRow = ['-', '-', '-']

board()